### ISSUE TITLE
Especificar el requerimiento de un modulo

### ISSUE THREAD

**Issue by Yix-Soviet** [JelsinPalomino/Trivia_entregable#1]
### Que pasa?
Falta especificar el requerimiento de un modulo esencial en el [README.md](https://github.com/JelsinPalomino/Trivia_entregable1/blob/main/README.md) para evitar problemas como estos: 

```sh
 Traceback (most recent call last):
  File "/Trivia_entregable1/main.py", line 5, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by JelsinPalomino** [comment]
De acuerdo, se me olvido especificar el uso de ese modulo. Lo agregare, muchas gracias.
